name: RvLabs-Node-App

on:
  push:
    paths: 
      - 'express-api/expapi/**'

env:
  AZURE_WEBAPP_NAME: rvlabs-express-api    # set this to your application's name
  NODEAPP_PACKAGE_PATH: 'express-api/expapi'      # set this to the path to your web app project, defaults to the repository root
  NODEAPP_PATH: 'express-api/expapi'
  NODE_VERSION: '12.13.0' 

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: npm install, build, and test
      working-directory: ${{ env.NODEAPP_PATH }}
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        npm install

    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.RVLABS_NODE_PUBLISH_PROFILE }}
        package: ${{ env.NODEAPP_PACKAGE_PATH }}
