name: RvLabs-Echo-Function

on:
  push:
    paths: 
      - 'funcapi/**'

env:
  AZURE_FUNCAPP_NAME: rvlabs-api    # set this to your application's name
  PKG_PATH: ${{ github.workspace }}/output     # set this to the path to your web app project, defaults to the repository root
  WORK_PATH: 'funcapi'
  DOTNET_VERSION: '3.1.300'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
      with:
        # SDK version to use. Example: 2.2.104
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Publish functions
      working-directory: ${{ env.WORK_PATH }}
      run: dotnet publish --configuration Release --output ${{ env.PKG_PATH }}

    - name: Azure Functions Action
      uses: Azure/functions-action@v1.1.4
      with:
        app-name: ${{ env.AZURE_FUNCAPP_NAME }}
        package: ${{ env.PKG_PATH }} # optional, default is .
        publish-profile: ${{ secrets.RVLABS_API }} # optional

